on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Build-Release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Check Go version
        run: go version
      - name: Build for Windows
        run: go build ./cmd/certlist
      - name: Get Latest MariaDB
        run: go run ./cmd/mdownload
      - name: Copy config.yaml
        run: Copy-Item -Path "cmd\certlist\config.yaml" -Destination ".\config.yaml" -Force
      - name: Pack release
        run: Compress-Archive -Path certlist.exe,mariadb-latest.zip,config.yaml -DestinationPath certlist_windows.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            certlist_windows.zip
